In [113]:
a = [1, 2, 3, 4, 5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


## NumPy

NumPy (**Num**eriacal **Py**thon) is an open source Python library that aids in mathemaical and scientific programming.

NumPy is the fundamental package for scientific computing with Python, It contains:

* a powerful N-dimensional array object
* extension package to Python for multi-dimensional arrays
* designed for scientific computation -- linear algebra and statistical oparations capabilities
* NumPy is increadible library to perform mathematical and statistical operations due to it's fast and memory effcient.
* This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.


In [114]:
##Import NumPy
import numpy as np

**bdarray object**

The basic ndarray is created using an array function NumPy as follows:

   numpy.array(object)

**Note**: In NumPy, axis = 0 is cols and axis = 1 is rows.

In [115]:
a = [1, 2, 3, 4, 5]
np_a = np.array(a)

In [116]:
print(np_a)

[1 2 3 4 5]


In [117]:
print(type(np_a))

<class 'numpy.ndarray'>


## Creating NumPy Arrays From a List

**1 - D**

In [118]:
a = np.array([0, 1, 2, 3])
print(a)
print(a.ndim)    # print diamesions
print(a.shape)   #print shape

[0 1 2 3]
1
(4,)


**2 - D**

In [119]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)
print(b.ndim)
print(b.shape)


[[0 1 2]
 [3 4 5]]
2
(2, 3)


In [120]:
# We can Convert a matrix which is also a list to array

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)
b = np.array(my_matrix)
print(b)
print(b.ndim)
print(b.shape)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


#### Functions for creating arrays

**arange**
- arange is an array-valued version of the built-in Python range function
- **Syntax:**  np.arange(start, end , step)

In [121]:
np.arange(10, 100, 10)   # Start, end (exclusive), step

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

**linspace**
- Return evenly spaced numbers over a specified interval.
- **Syntax:** np.linspace(start, end, num_of_samples)

In [122]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**zeros**
- Generate array of zeros
- **Syntax:** np.zeros(shape)

In [123]:
np.zeros((3))

array([0., 0., 0.])

In [124]:
np.zeros((3,3)) # zero matrix or null matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**random.randint**
- return random integers from start(inclusive) to end (exclusive)
- **Syntax:** np.random.rad=ndint(start, end, num_of_samples) 

In [125]:
np.random.randint(1, 41, 5)

array([ 1,  1,  5,  7, 21], dtype=int32)

### Operations

**Flattening :** Converting nd array to 1D array

In [126]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

a.ravel()

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

**Reshape array**

In [127]:
arr = np.arange(20)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [128]:
# Notice the two sets of brackets
a1 = arr.reshape(5,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [129]:
a = np.array([[1,2,3], [4, 5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [130]:
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


**Transpose array**

In [131]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [132]:
c = a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


**Copy array**

In [133]:
a = np.array([1, 2, 3])
b = a    # shallow copy
b[0] =100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [134]:
a = np.array([1,2,3])
b = a.copy()               #carbon copy or deep copy
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


**Sort**

In [135]:
np.sort([4,5,1,6,9,8,2,3,7,0])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
# Sorting along an axis: axis = 1---> row and axis = 0 ---> column

a= np.array([[5,4,6],[2,8,2]])
b = np.sort(a)
b

array([[4, 5, 6],
       [2, 2, 8]])

**Add/Remove operations on a numpy array**

In [137]:
a = np.array([4,7,8])

print('Numpy array before addition :',a)

a = np.append(a, [2,3,4])
print('Numpy array after addition :',a)

a = np.delete(a, 2)   # deleting index[2] element  i.e. 8
print('Numpy array agter deletion of one element: ',a)   

Numpy array before addition : [4 7 8]
Numpy array after addition : [4 7 8 2 3 4]
Numpy array agter deletion of one element:  [4 7 2 3 4]


**Indexing**

In [138]:
a = np.arange(3, 10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [139]:
a[5]= 50
print(a)

[ 3  4  5  6  7 50  9]


In [140]:
a  = np.diag([1, 2, 3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [141]:
print(a[2, 1])

0


In [142]:
a[2, 1] = 5   # assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**Indexing with an array  of integers**

In [143]:
a = np.arange(0, 101, 10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [144]:
a[2]

np.int64(20)

In [147]:
# Indexing can be done with an array of integers
a[[2,3,2,4,9]]


array([20, 30, 20, 40, 90])

In [149]:
a[2] =100

In [151]:
# New values can be assigned
a[[1, 10]]= 1000
a

array([   0, 1000,  100,   30,   40,   50,   60,   70,   80,   90, 1000])

**Mask Indexing or Fancy Indexing**

In [152]:
a = np.array([12,5,6,21,16,4])

In [153]:
a

array([12,  5,  6, 21, 16,  4])

In [154]:
a%2 == 0

array([ True, False,  True, False,  True,  True])

In [155]:
a[a%2==0]

array([12,  6, 16,  4])

**Slicing**

In [156]:
a = np.arange(4, 18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [157]:
a[1:8:2]      # [ Startindex: endidex(exclusive): step]

array([ 5,  7,  9, 11])

**Arithmatic Operations**

In [159]:
a = np.array([1, 2, 3, 4])  
print(a)

[1 2 3 4]


In [160]:
print(a+1)

[2 3 4 5]


In [161]:
a ** 2

array([ 1,  4,  9, 16])

In [162]:
b = np.ones((4 ,)) +1
b

array([2., 2., 2., 2.])

In [163]:
a + b

array([3., 4., 5., 6.])

In [164]:
a-b

array([-1.,  0.,  1.,  2.])

In [165]:
a *b

array([2., 4., 6., 8.])

In [167]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[4,4],[4,4],[4,4]])


# adding and b
print(a+b)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [168]:
# multipy a and b - elementwise multiplication
print(a*b)

[[ 4  8]
 [12 16]
 [20 24]]


In [169]:
# matrix multiplication
a = np.array([[1, 2, 1], [3, 4, 3], [5, 6,5]])
b = np.array([[4, 4,1], [4, 4, 2], [4, 4, 3]])
np.matmul(a, b)

array([[16, 16,  8],
       [40, 40, 20],
       [64, 64, 32]])

**Comparision Operations**

In [171]:
a = np.array([1,2, 3,4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [172]:
a>b

array([False, False,  True, False])

In [174]:
# array wise comparisions
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])


In [175]:
np.array_equal(a,b)


False

In [176]:
np.array_equal(a,c)

True

**Mathematical Operations**

In [177]:
a = np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [178]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [179]:
np.log(a)

C:\Users\abhay\AppData\Local\Temp\ipykernel_13368\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

In [181]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])