In [2]:
import numpy as np


In [3]:
x = np.array(np.random.randint(140, 200, 9))
x

array([167, 164, 160, 199, 184, 155, 173, 142, 145], dtype=int32)

## Sum

In [4]:
np.sum(x)

np.int64(1489)

## Meana

In [5]:
# option 1

np.sum(x)/len(x)

np.float64(165.44444444444446)

In [7]:
# option 2

np.mean(x)

np.float64(165.44444444444446)

In [8]:
# option 3

x.mean()

np.float64(165.44444444444446)

## Median

In [11]:
np.median(x)

np.float64(164.0)

## Mode

In [12]:
from scipy.stats import mode

mode(x)

ModeResult(mode=np.int32(142), count=np.int64(1))

## Minimum

In [13]:
np.min(x)

np.int32(142)

In [14]:
x.min()

np.int32(142)

In [15]:
# index of minimum element

np.argmin(x)

np.int64(7)

## Maximum

In [16]:
np.max(x)

np.int32(199)

In [17]:
x.max()

np.int32(199)

In [18]:
# index of maximum element

np.argmax(x)

np.int64(3)

## Range

In [19]:
x.max() - x.min()

np.int32(57)

# Mean Absolute Deviation 

In [22]:
x =np.array(np.random.randint(1, 20, 5))
x

array([ 6, 14, 16, 18, 17], dtype=int32)

In [23]:
deviation = x - x.mean()
deviation

array([-8.2, -0.2,  1.8,  3.8,  2.8])

In [24]:
abs_deviation = abs(deviation)
abs_deviation

array([8.2, 0.2, 1.8, 3.8, 2.8])

## Mean Square Deviation

In [25]:
x = np.array(np.random.randint(1, 20, 5))
print('x :', x)
deviation = x-x.mean()
print('Deviation: ', deviation)
sqr_deviation = deviation * deviation
print('Square Deviation: ', sqr_deviation)
print('Mean Square Deviatioin: ', np.mean(sqr_deviation))


x : [11  6 12  8  1]
Deviation:  [ 3.4 -1.6  4.4  0.4 -6.6]
Square Deviation:  [11.56  2.56 19.36  0.16 43.56]
Mean Square Deviatioin:  15.440000000000001


## Vaariance / Mean Square Deviation

In [26]:
np.var(x)

np.float64(15.440000000000001)

- Default Population Variance

## Standard deviation

In [27]:
# option 1

var = np.var(x)
std = np.sqrt(var)
std

np.float64(3.9293765408777004)

In [29]:
# option 2

np.std(x)

np.float64(3.9293765408777004)

## Sample Variance & Sample Standard

## Deviation

In [30]:
s = np.array(np.random.randint(1000, 2500, 4))
s

array([1241, 1706, 2464, 1073], dtype=int32)

In [31]:
sample_variance = np.var(s) * len(s)/ len((s-1))
sample_variance

np.float64(290644.5)

In [32]:
sample_std_dev = np.sqrt(sample_variance)
sample_std_dev

np.float64(539.1145518347654)

## Percentile

In [34]:
ages = np.random.randint(1, 101, 21)
ages

array([60, 91, 91, 14, 73, 24, 46, 44, 80, 68, 52, 51, 64, 49,  7, 56, 86,
       52, 59, 71,  4], dtype=int32)

In [35]:
np.percentile(ages, 25)

np.float64(46.0)

In [36]:
np.percentile(ages, 75)

np.float64(71.0)

In [38]:
np.percentile(ages, [25, 50, 75])

array([46., 56., 71.])